version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:4a:13:57:44:6f:d4:32:64:09:9a:57:13:b0:88:bd"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/home/ec2-user/var/www/Atlier/deploy-me.sh"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: develop