version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e6:84:74:a9:e1:ec:04:1c:36:f0:2a:23:81:d7:3c:7b"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/home/ec2-user/var/www/Atlier/deploy-me.sh"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: develop