default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: <%= ENV["MYSQL_HOST"] %>
  database: <%= ENV["MYSQL_NAME"] %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>


development:
  <<: *default

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_prod
