password_length:
  range: 8..128
  minimum: 8
attached_count:
  maximum: 5
  addition: 1
regular_expressions:
  email: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
avatar_size:
  in_part: 20
  in_header: 22
  in_feed: 32
  in_aside: 78
  in_profile: 150
default_image:
  avatar: "avatar.png"
  work: "choice_image.png"