require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("bootstrap")
require("jquery")
require('./image_preview')
require('./category')
require('./alert')
import "bootstrap"