require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("bootstrap")
require("jquery")
require('./category')
require('./form')
require('./image')
import "bootstrap"